### ISSUE TITLE
曲目过多的歌单不点入详情无法全部播放

### ISSUE THREAD

**Issue by 1818yu** [GuMengYu/v-player#14]
![image](https://user-images.githubusercontent.com/56754498/195577697-9e37e105-f134-4a2c-b7f3-c2fe4acc9125.png)
在主页与音乐库点播放全部不会有效果，正在播放的音乐还会继续播放。“曲目过多”的数量我感觉是1000+，打开歌单后点全部播放可以正常工作

**Comment by GuMengYu** [comment]
歌单id发一下呢 到详情页可以跳到music.163 的网页，地址栏有id 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/22021419/195991830-9ede2cb2-12b5-4010-8255-de257e58f179.png">

**Comment by GuMengYu** [comment]
> ![image](https://user-images.githubusercontent.com/56754498/195577697-9e37e105-f134-4a2c-b7f3-c2fe4acc9125.png)
> 在主页与音乐库点播放全部不会有效果，正在播放的音乐还会继续播放。“曲目过多”的数量我感觉是1000+，打开歌单后点全部播放可以正常工作

看了下应该是网易云的限制播放列表限制了1000首，然后接口报错了。我加上1000的限制 fixed: 86a3dac80fedc6a3e5ff2bc63b34447b4d4ba8e9
