### ISSUE TITLE
搜索框的样式和界面内其他样式不一样有点不协调的感觉

### ISSUE THREAD

**Issue by SoDebug** [GuMengYu/v-player#16]
这是搜索框的
![image](https://user-images.githubusercontent.com/30922923/204119919-e7555c0f-d26d-4489-be82-85e475dee110.png)
这是设置内的
![image](https://user-images.githubusercontent.com/30922923/204119929-f1dc4a97-bbae-44cf-a2a8-b0e6789c6707.png)

**Comment by SoDebug** [comment]
感觉可以在点击搜索的时候，做一个全局面的布局，如下：
![EEE82D18A9F5F5CD456EE4542C29F2E7](https://user-images.githubusercontent.com/30922923/204119977-3ace7751-baf6-4c85-97cc-8447c8299bd0.png)

**Comment by GuMengYu** [comment]
> 感觉可以在点击搜索的时候，做一个全局面的布局

感觉没必要哈，手机的逻辑

**Comment by GuMengYu** [comment]
小调整了一下

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/22021419/204230493-123a0c9c-15b1-4a9b-b28a-766f409d6ef9.png">
