### ISSUE TITLE
希望可以增加取色引擎（类似Android 13 的Monet）

### ISSUE THREAD

**Issue by SoDebug** [GuMengYu/v-player#17]
这里指的取色不是指的取系统壁纸的颜色（应该难度很大，可能没有相关的接口）
想的是取专辑图片的颜色，举例如下：
这首歌，专辑主体呈乳白色，则取色引擎获得专辑颜色后，整个主题界面呈现不同程度的偏乳白的的色调
![93C23042BF233A8E06DA2E193FFEF58D](https://user-images.githubusercontent.com/30922923/204120122-ff6892f5-e9dc-4e1f-80c3-47b369b9476d.png)
这首歌，专辑主体呈蓝调，则取色引擎获得专辑颜色后，整个主题界面呈现不同程度的蓝调的的色调
![623CD7E676E495C7892D23546EA5430C](https://user-images.githubusercontent.com/30922923/204120141-88ffa338-ea7c-47d2-8145-b340baa35d78.png)

**Comment by GuMengYu** [comment]
这是什么app 我去借鉴下☺️

**Comment by SoDebug** [comment]
> 这是什么app 我去借鉴下☺️

music you，这个软件正在筹备开源，这是该apk：https://www.123pan.com/s/G4F0Vv-5HJ4

**Comment by GuMengYu** [comment]
可能暂时不考虑做这个 按专辑取色更改全局主题
分析专辑生成主题有一定的性能损耗， 频繁切换不太合理。
目前可以上传自定义的图片生成一份 md3主题色，来自 https://m3.material.io/theme-builder#/dynamic
