### ISSUE TITLE
播放一段时间后就停止播放

### ISSUE THREAD

**Issue by SoDebug** [GuMengYu/v-player#4]
正常播放音乐一段时间后，就停止播放了，并且点 播放键 无反应，切换下一首或者点击其他音乐才能继续播放

客户端版本：vplayer-next.2.0.2
Windows版本：Windows 11 专业工作站版 22H2（22622.586） /  Windows Feature Experience Pack 1000.22634.1000.0

**Comment by GuMengYu** [comment]
是某一首歌曲吗？
不太好重现，可能是歌曲加载的问题
ctrl+ r 可以刷新，重新播放试试

**Comment by SoDebug** [comment]
> 是某一首歌曲吗？ 不太好重现，可能是歌曲加载的问题 ctrl+ r 可以刷新，重新播放试试

感觉也是加载问题，重新播放可以正常播放，不过好多首都是这样。
