### ISSUE TITLE
部署到 vercel

### ISSUE THREAD

**Issue by tylvn** [GuMengYu/v-player#5]
问一下该项目如何自己部署到 vercel 上？部署到 vercel 上后的体验与桌面客户端有什么区别？

**Comment by GuMengYu** [comment]
vercel 部署直接`npm run build` 打包，然后部署`dist/renderer`下面的静态文件到 vercel 就行了

另外需要自己部署[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 的接口，见：https://github.com/Binaryify/NeteaseCloudMusicApi#vercel-%E9%83%A8%E7%BD%B2

两者功能上区别不是很大，体验上vercel托管的接口请求加载可能有点慢，体验不是很好。
