### ISSUE TITLE
是否可以打包一个apk用于安卓客户端？

### ISSUE THREAD

**Issue by smile31768** [GuMengYu/v-player#7]
请问是否有计划打包一个apk呢？

**Comment by GuMengYu** [comment]
> 请问是否有计划打包一个apk呢？

不行 这是web 技术加electron。

**Comment by smile31768** [comment]
那是否有考虑在未来支持下pwa呢？

**Comment by smile31768** [comment]
> > 请问是否有计划打包一个apk呢？
> 
> 不行 这是web 技术加electron。

那是否有考虑在未来支持下pwa呢？
